name: Hello World

on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: [self-hosted, TISA]
    steps:
      - name: Echo Hello World
        shell: powershell
        run: echo "helloworld"
        
